### ISSUE TITLE
It won't open

### ISSUE THREAD

**Issue by razouck** [tomscii/zutty#103]
Zutty doesn't seem to be able to find most of my installed fonts.
`~ $ zutty -font dejavusansmono
W [fontpack.cc:306] Warning: Failed to locate requested double-width font: 18x18ja
~ $ zutty -font martianmono
E [fontpack.cc:218] Error: No Regular variant of the requested font 'martianmono' could be identified.
terminate called after throwing an instance of 'std::runtime_error'
  what():  No suitable files for 'martianmono' found!
Abortado (imagem do núcleo gravada)
~ $ zutty -font martianmonostdrg
E [fontpack.cc:218] Error: No Regular variant of the requested font 'martianmonostdrg' could
be identified.
terminate called after throwing an instance of 'std::runtime_error'
  what():  No suitable files for 'martianmonostdrg' found!
Abortado (imagem do núcleo gravada)
~ $ zutty -font inconsolata
E [fontpack.cc:218] Error: No Regular variant of the requested font 'inconsolata' could be identified.
terminate called after throwing an instance of 'std::runtime_error'
  what():  No suitable files for 'inconsolata' found!
Abortado (imagem do núcleo gravada)
~ $ zutty -font jetbrainsmono
E [fontpack.cc:218] Error: No Regular variant of the requested font 'jetbrainsmono' could be
identified.
terminate called after throwing an instance of 'std::runtime_error'
  what():  No suitable files for 'jetbrainsmono' found!
Abortado (imagem do núcleo gravada)
~ $ zutty -font 'JetBrains Mono'
E [fontpack.cc:218] Error: No Regular variant of the requested font 'JetBrains Mono' could be identified.
terminate called after throwing an instance of 'std::runtime_error'
  what():  No suitable files for 'JetBrains Mono' found!
Abortado (imagem do núcleo gravada)
`

**Comment by tomscii** [comment]
Read the docs and the FAQ

**Comment by razouck** [comment]
I should've done that from the beginning. I apologize.

Thank you.
