### ISSUE TITLE
Changing keyboard layout generates Ctrl+2

### ISSUE THREAD

**Issue by Gliese852** [tomscii/zutty#104]
Judging by the log of the `xev` utility, pressing the key combination to change the keyboard layout (just `Caps lock` in my case) leads to the generation of the following event:
```
KeyPress event, serial 34, synthetic NO, window 0x4e00001,
    root 0x6c3, subw 0x0, time 5997674, (957,514), root:(961,534),
    state 0x0, keycode 66 (keysym 0xfe08, ISO_Next_Group), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False
```

In the `onKeyPress` function, this symbol code is not processed in any way and is not filtered, which leads to sending a buffer of zeros to the function `zutty::Vterm::writePty`. 
This is how the debug output of `zutty` looks like:
```
[vterm.cc:739] pty write (mod=0): '\x00' (1 bytes)
[vterm.cc:821] pty write: '\x00' (1 bytes)
```
Then, this is perceived by the terminal as `Ctrl+2`, which leads, for example, to the output of the character `^@` in the cat utility, and to call the commands corresponding to this combination, for example, in `vim` or `emacs`.

For myself, I solved this problem by adding the line
```
KEYIGN (XK_ISO_Next_Group);
```
to the appropriate place in the `onKeyPress` function. But maybe this is the wrong solution, and maybe other keysyms should be filtered out as well, I don't know.

**Comment by tomscii** [comment]
Thanks for the excellent write-up!

Looking at `/usr/include/X11/keysymdef.h` I would say that all syms in the block between `XK_ISO_Group_Shift` and `XK_ISO_Last_Group_Lock` can be safely ignored (this includes `XK_ISO_Next_Group`).
