### ISSUE TITLE
':', '<', '=' and '?' cancels control sequence

### ISSUE THREAD

**Issue by zsugabubus** [tomscii/zutty#106]
As far as I know, these are perfectly valid parameter bytes (3/00-3/15) that should not cancel control sequences.

```
$ printf '\x1b[1:2m\x1b[1<3m\x1b[1=4m'
2m3m4m
$ printf '\x1b[??m'
m
```

```
E [vterm.icc: 91] Error: Unhandled input char ':' (58) in state CSI. Escape sequence so far: '\e[1:' (4 bytes)
E [vterm.icc: 91] Error: Unhandled input char '<' (60) in state CSI. Escape sequence so far: '\e[1<' (4 bytes)
E [vterm.icc: 91] Error: Unhandled input char '=' (61) in state CSI. Escape sequence so far: '\e[1=' (4 bytes)
E [vterm.icc: 91] Error: Unhandled input char '?' (63) in state CSI_priv. Escape sequence so far: '\e[??' (4 bytes)
```

**Comment by tomscii** [comment]
I don't think these are "perfectly valid parameter bytes" at all.

DEC STD 070 has this to say:

> 3.5.3.1 Parameter values in control sequences
> 
> The bit combination 3/10 is reserved for future standardization. If 3/10 is received within a parameter string, the entire sequence up to and including the final character shall be ignored. Bit combinations 3/12 through 3/15 are used for private parameter strings (see subhead 3.5.3.4).
> 
> 3.5.3.4 Private parameter strings
> 
> If bit combinations 3/12 through 3/15 occur anywhere else in the control sequence other than as the first character of the parameter string, the entire sequence up to and including the final character shall be ignored.

(For bystanders: 3/10 is ':', 3/11 is ';', 3/12 is '<', 3/13 is '=', 3/14 is '>' and 3/15 is '?'.)

I interpret the issue as Zutty not ignoring the erroneous control sequence up to the final character, only up to the illegal character (and hence sending the rest to the shell, which will most likely echo it).

**Comment by zsugabubus** [comment]
Quotations are about the interpretation of the formed parameter string and they do not refute my statement that these are "perfectly valid parameter bytes". They are valid parameter bytes, that's why they can be part of the parameter string. It is otherwise a valid action from a valid byte to make the sequence ignored. I see no error here. /s

**Comment by tomscii** [comment]
Okay, whatever, I am not a lawyer. Do you agree with my interpretation of the issue?
