### ISSUE TITLE
can i get some help with the config file?

### ISSUE THREAD

**Issue by darkralts** [tomscii/zutty#107]
im trying to figure out persistent configuration, i found the https://github.com/tomscii/zutty/blob/master/doc/USAGE.org, but https://github.com/tomscii/zutty/blob/master/doc/Extra%20resources and https://github.com/tomscii/zutty/blob/master/doc/Persistent%20configuration dont exist, which is what im looking for, how do i create a config file? is there an example config? i dont really want to use the command line method if possible

**Comment by tomscii** [comment]
Please look here for the properly rendered org-doc instead: https://tomscii.sig7.se/zutty/doc/USAGE.html
Alas, I cannot turn off GitHub's half-assed rendering shown on github (which is what you linked to above), that breaks links unfortunately.
