### ISSUE TITLE
Intermittent startup failure

### ISSUE THREAD

**Issue by ILoveGoulash** [tomscii/zutty#109]
Using zutty 0.13 on Gentoo, the following happens randomly (something like 1/4 of all tries):
```
$ zutty -verbose -font ter-x16n -fg '#aaaaaa'
Error: couldn't open display '#aaaaaa'
```
when it usually shows:
```
Zutty 0.13
Copyright (C) 2020 Tom Szilagyi

This program comes with ABSOLUTELY NO WARRANTY.
Zutty is free software, and you are welcome to redistribute it
under the terms and conditions of the GNU GPL v3 (or later).

I [font.cc: 77] Loading /usr/share/fonts/terminus/ter-x16n.pcf.gz as primary
I [font.cc:243] Glyph size 8x16
I [font.cc: 77] Loading /usr/share/fonts/misc/18x18ja.pcf.gz as double-width
W [fontpack.cc:313] Warning: Failed to load double-width font: /usr/share/fonts/misc/18x18ja.pcf.gz: size mismatch, expected px=16, got: 18
I [main.cc:171] Window ID: 35651586 / 0x2200002
I [charvdev.cc:509] Resize to 1260 x 692 pixels, 157 x 43 chars
```
for the same command line and starts correctly.

**Comment by tomscii** [comment]
Please work on reproducing this with the latest master, and narrow it down as much as possible.
I.e., is the choice of font critical? Does it happen with Zutty compiled for debugging as well? Can you reproduce it on something different than your Gentoo system? Etc.

**Comment by ILoveGoulash** [comment]
Looks like this is a 0.13 only problem, but it happens even with the following command line: `zutty -shell /bin/false`

Used
```
for i in {0..100}; do zutty -shell /bin/false >/dev/null 2>&1 || { echo "FAIL at i=$i"; break; }; done
````
to test the problem

**Comment by tomscii** [comment]
I just checked out and built 0.13 to test this, but I cannot reproduce your issue even with that version. This is on Debian stable.
(Also ran your reproducer above on latest master, no FAIL there either.)
Feel free to reopen in case it appears in the latest version.
