### ISSUE TITLE
Window title is set incorrectly when using custom unicode characters

### ISSUE THREAD

**Issue by ixolius** [tomscii/zutty#112]
## What I want:
I want to set the window title to something like this: 端末
## What I tried:
Using xresources and setting:
```
Zutty.title = "端末"
```
Using the command-line option: `zutty -title 端末`
## What I get
- Plasma (one window manager) doesn't display a title at all
- i3wm (another window manager) displays some gibberish (I found no way to paste it here) as the title
- polybar (my status bar) displays the same gibberish as i3 as the title

## More infos
I have no problems with CJK chars in the title when using other programs. I think, this is because zutty uses `WM_NAME` instead of `_NET_WM_NAME` (see https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html and https://github.com/eXeC64/imv/issues/224), but honestly, I'm not very familiar with this subject.

**Comment by ixolius** [comment]
I played around a bit, and I might have found an idea: I tried to set `_NET_WM_NAME` in the `main.cc`, but I'm not sure how to call `XChangeProperty` using the given name.
If I use
```
     XChangeProperty (xDisplay, xWindow, _NET_WM_NAME, UTF8_STRING,
                      8, PropModeReplace, (const unsigned char *) name, 1);
```
the title is displayed incorrectly.
If I use
```
     XChangeProperty (xDisplay, xWindow, _NET_WM_NAME, UTF8_STRING,
                      32, PropModeReplace, (const unsigned char *) name, 1);
```
only the first character is displayed correctly and `xprop` tells me: `Type mismatch: assumed size 8 bits, actual size 32 bits.`
It looks like the `name` parameter itself is not correctly encoded but I'm not sure. If wanted, I can file a PR and we discuss the code there.

**Comment by tomscii** [comment]
Have you tested with xterm? Does it work?
I.e., if you run `xterm -title 端末` does that window have the right title?
On my machine it does not seem so, see attached screenshot.
![xterm_title_cjk](https://user-images.githubusercontent.com/5454768/223649090-d977096e-b324-4ab8-b642-2dda1f7f4a2f.png)
The gibberish in the title looks identical to what I see when trying zutty, is that what you see as well?

**Comment by ixolius** [comment]
> Have you tested with xterm? Does it work?
> I.e., if you run xterm -title 端末 does that window have the right title?
No, it looks like what you are seeing.
> The gibberish in the title looks identical to what I see when trying zutty, is that what you see as well?
Yes, that matches.

**Comment by tomscii** [comment]
FWIW, the xprop on the window of `zutty -title 端末` has this out of the box:
```
WM_NAME(COMPOUND_TEXT) = "端末"
```
i.e., it looks correct (and exactly identical to how xterm behaves).

I also got xprop to report a seemingly correct _NET_WM_NAME:
```
_NET_WM_NAME(UTF8_STRING) = "端末"
```
by using the below snippet.

The title bar still does not display correctly (now I get two "glyph missing" rectanges which is less wrong, as there should be two CJK glyphs), but I think that is just because I don't have a CJK-capable font set in my i3.

So I think you almost nailed it, you just forgot about the length (left as 1).

Does this work for you?
```
modified   src/main.cc
@@ -214,6 +214,14 @@ makeXWindow (const char* name, int width, int height, int px, int py,
                        sizeof (wm_icons) / sizeof (wm_icons [0]));
    }
 
+   {
+      Atom UTF8_STRING = XInternAtom (xDisplay, "UTF8_STRING", false);
+      Atom _NET_WM_NAME = XInternAtom (xDisplay, "_NET_WM_NAME", false);
+      XChangeProperty (xDisplay, xWindow, _NET_WM_NAME, UTF8_STRING,
+                       8, PropModeReplace, (const unsigned char*) name,
+                       strlen (name));
+   }
+
    wmDeleteMessage = XInternAtom (xDisplay, "WM_DELETE_WINDOW", False);
    XSetWMProtocols (xDisplay, xWindow, &wmDeleteMessage, 1);
 
```

If that works, then of course one has to treat `handleOsc ()` as well...

**Comment by ixolius** [comment]
Applying your patch gives me
![zutty_works](https://user-images.githubusercontent.com/37013742/223705037-9e14845f-39bc-4196-8337-a4008e3bc1cf.png)
so yeah, that works!


I have a follow-up question: When configuring the title via `xrdb`, I cannot set those characters. If I set them as-is, they get transformed into `U00007aefU0000672b`. If I enclose them in quotes (singe or double), they stay as they are, but the quotes also get passed to the title. Is this a zutty problem (if so, I'll file a new issue)? Or is this `xrdb`?

**Comment by tomscii** [comment]
No idea about xrdb, I don't think it was ever designed to work with Unicode. Clearly, the U000... thing is some ascii rendering of the two CJK glyphs (U+7AEF U+672B), so that comes closest. But that's still just a flat string coming out of `XGetDefault()` and I'd rather not add any "clever" code there to parse that into a proper UTF-8 string. Feel free to dig further into this and let me know if you find something.

But, you should be able to set the title programmatically by something like `printf "\e]0;端末\e\\"`, and if you put that in your .bashrc or equivalent, that will get you pretty close I think. (You need my current patch, see below.)

```
modified   src/main.cc
@@ -107,6 +107,29 @@ setXCursor ()
    XDefineCursor (xDisplay, xWindow, cursor);
 }
 
+static void
+setUtf8prop (const char* prop_name, const std::string & value)
+{
+   Atom utf8 = XInternAtom (xDisplay, "UTF8_STRING", false);
+   Atom prop = XInternAtom (xDisplay, prop_name, false);
+   XChangeProperty (xDisplay, xWindow, prop, utf8, 8, PropModeReplace,
+                    (const unsigned char*) value.data (), value.size ());
+}
+
+static void
+setXWindowName (const std::string & name)
+{
+   XStoreName (xDisplay, xWindow, name.c_str ());
+   setUtf8prop ("_NET_WM_NAME", name);
+}
+
+static void
+setXWindowIconName (const std::string & name)
+{
+   XSetIconName (xDisplay, xWindow, name.c_str ());
+   setUtf8prop ("_NET_WM_ICON_NAME", name);
+}
+
 static void
 makeXWindow (const char* name, int width, int height, int px, int py,
              EGLDisplay eglDpy, EGLContext& eglCtx, EGLSurface& eglSurface)
@@ -214,6 +237,12 @@ makeXWindow (const char* name, int width, int height, int px, int py,
                        sizeof (wm_icons) / sizeof (wm_icons [0]));
    }
 
+   {
+      std::string title {name};
+      setXWindowName (title);
+      setXWindowIconName (title);
+   }
+
    wmDeleteMessage = XInternAtom (xDisplay, "WM_DELETE_WINDOW", False);
    XSetWMProtocols (xDisplay, xWindow, &wmDeleteMessage, 1);
 
@@ -1086,14 +1115,14 @@ handleOsc (int cmd, const std::string& arg)
    switch (cmd)
    {
    case 0: // Change Icon Name & Window Title
-      XStoreName (xDisplay, xWindow, arg.c_str ());
-      XSetIconName (xDisplay, xWindow, arg.c_str ());
+      setXWindowName (arg);
+      setXWindowIconName (arg);
       break;
    case 1: // Change Icon Name
-      XSetIconName (xDisplay, xWindow, arg.c_str ());
+      setXWindowIconName (arg);
       break;
    case 2: // Change Window Title
-      XStoreName (xDisplay, xWindow, arg.c_str ());
+      setXWindowName (arg);
       break;
    case 52: // Manipulate Selection Data
    {
```

**Comment by ixolius** [comment]
Applying your patch allows me to set unicode titles via the `-title` argument. Thank you for the quick fix! It's awesome that zutty's very good unicode support now extends to the window title ;-)
Regarding `xrdb`: Don't worry, maybe I'll find a way, maybe not. For the moment, I have `alias`, `.desktop` files and my WMs configuration, so I'll find a way to pass my custom title to zutty.
