### ISSUE TITLE
How to pass args with --shell switch.

### ISSUE THREAD

**Issue by Tracnac** [tomscii/zutty#115]
Hello,

First thanks for this very good project.

My concern, unable to pass arguments to the --shell switch.
Neither " or ' do the job...

For example: --shell pathToMyBinary SomeArgsToIt

```shell
zutty --shell /usr/bin/tmux -f conf.tmux
```

Thanks Yvan

PS: I'm not looking at the code yet...

**Comment by tomscii** [comment]
What you want is `-e` as per https://tomscii.sig7.se/zutty/doc/USAGE.html#Shell%2Fcommand%20specification

**Comment by Tracnac** [comment]
Humm ok, sorry I completely misunderstood the switch...
I thought that you run a shell with -e, it's why I focused on the --shell option, cause I want the program to launch directly without any shell.

Thanks Again.
