### ISSUE TITLE
RGB color gets overwritten by certain SGR codes

### ISSUE THREAD

**Issue by dariof4** [tomscii/zutty#117]
If a fg/b color is set using SGR code 38;2/48;2 (38;5 and 48;5 work fine since they set `fgPalIx`/`bgPalIx`) and then an SGR code that uses `setFgFromPalIx`/`setBgFromPalIx` is used, the color gets overwritten.

Example:
`printf "\x1b[38;2;255;0;0mhello"` correctly prints a red hello.
`printf "\x1b[38;2;255;0;0;22mhello"` prints hello with the default fg color instead being red.

I looked at the code and I think I found the culprit, SGR codes 38;5 and 48;5 don't set `fgPalIx` and `bgPalIx` respectively, instead they directly apply the color to fg/bg, because of this the color gets overwritten when an escape sequence calls `setFgFromPalIx` or `setBgFromPalIx`, this can happen with the following SGR codes: 1, 2, 7, 10..19,  22 and 27 (the SGR codes to set color from the pallet and reset color also call `setFgFromPalIx` /`setBgFromPalIx`, but since they set `fgPalIx`/`bgPalIx` they are meant to override the color).

Thanks for making zutty, I like how having low latency was something that was given thought, it makes zutty feel really snappy in practice :-)

**Comment by tomscii** [comment]
Thanks for reporting!
