### ISSUE TITLE
Resizing bug when DPI != 100%

### ISSUE THREAD

**Issue by nagalun** [tomscii/zutty#118]
Hello,

I have noticed that the terminal currently has buggy behavior at least on Wayland when scaling is used. In my case the scaling is set to 125%.
When first opened up it renders and works perfectly fine, the window can be moved around no problem.
![image](https://github.com/tomscii/zutty/assets/13302036/c997145b-6c2e-4e89-aae8-b9d4c8a9c153)

However when it gets resized/maximized it enters some kind of loop and starts decreasing the window height until there's only one row:
![image](https://github.com/tomscii/zutty/assets/13302036/cc2f23cc-5910-4716-b74f-6585f37016f2)

I haven't looked at the code, but my first guess would be that it could be something related to the snap-to-char resizing behavior miscalculating how many pixels a character takes when scaling is applied.

If you need any more info let me know, and thanks for making this terminal emulator, it works really well on my low power ARM machine.

**Comment by tomscii** [comment]
I don't use Wayland, at least not directly (at the moment, I use Debian 12 with Xwayland).

Please compile Zutty with debug on and run it with trace output enabled (as documented in the [dev guide](https://tomscii.sig7.se/zutty/doc/HACKING.html)) to see if there is anything happening other than receiving resize events (as shown by your second screenshot).

**Comment by nagalun** [comment]
Well I have been playing around a bit with the code to see if I could figure it out, it seems like XSetWMNormalHints on main.cc:1004 produces strange behavior. When it gets called with the new width/height a new ConfigureNotify event comes through with the height set previously, minus a step based on the value of height_inc.

I dug a bit and it looks like the width and height fields are marked as obsolete, but changing them to base_height and base_width doesn't really fix anything: https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-normal-hints.html#XSizeHints

Interestingly commenting out the call to XSetWMNormalHints still makes the window resize with the right increments and the bug doesn't occur. When maximizing the window some transparent seams appear from the unusable extra area but otherwise looks like it works fine, so I'm not too sure of the purpose of the call.

I found the built in trace logs not useful and too noisy as there aren't any traces on the configure event so I added some quick prints:
![image](https://github.com/tomscii/zutty/assets/13302036/56340914-b124-4da0-9c55-71e29cb63bbd)

That gives me these entries when maximizing the window (the first event line is from window creation):

```
E [main.cc:999] Error: !!! WM CONFIGURE from 1204, 604 => to 1204, 604 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:999] Error: !!! WM CONFIGURE from 1204, 604 => to 1917, 991 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:1010] Error: calling XSetWMNormalHints
E [main.cc:999] Error: !!! WM CONFIGURE from 1917, 991 => to 1917, 991 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:999] Error: !!! WM CONFIGURE from 1917, 991 => to 1914, 984 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:1010] Error: calling XSetWMNormalHints
E [main.cc:999] Error: !!! WM CONFIGURE from 1914, 984 => to 1914, 984 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:999] Error: !!! WM CONFIGURE from 1914, 984 => to 1914, 964 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:1010] Error: calling XSetWMNormalHints
# lots of lines cut...
E [main.cc:999] Error: !!! WM CONFIGURE from 1914, 64 => to 1914, 64 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:999] Error: !!! WM CONFIGURE from 1914, 64 => to 1914, 44 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:1010] Error: calling XSetWMNormalHints
E [main.cc:999] Error: !!! WM CONFIGURE from 1914, 44 => to 1914, 44 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:999] Error: !!! WM CONFIGURE from 1914, 44 => to 1914, 24 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
E [main.cc:1010] Error: calling XSetWMNormalHints
E [main.cc:999] Error: !!! WM CONFIGURE from 1914, 24 => to 1914, 24 / border = 0, min_height=24, max_height=0, min_width=14, max_width=0, base_width=4, base_height=4, height_inc=20, win_grav=1
```

Here's what happens with the built in traces (unmodified program, built with debug and executed with -verbose):
[traces.txt](https://github.com/tomscii/zutty/files/11962389/traces.txt)

> I don't use Wayland, at least not directly (at the moment, I use Debian 12 with Xwayland).

I don't think I understood, but the terminal is indeed being run through XWayland, even though my desktop environment is wayland native.

**Comment by tomscii** [comment]
Thanks.

The original setting of the window size hints is at window setup; see line 209 and onward in main.cc. There the base and increment fields are set as well.

The call you highlighted is just an update so the actual size of the window is up to date (hence updating the obsolete-marked width and height fields). This update might well be redundant (I can't specifically remember the reason it was added - maybe I decided based on xprop output that it is needed? I don't recall), but has not caused any issues so far.

Out of curiosity, does this happen only if this scaling (is that a wayland thing?) happens to be >1? I.e., if you scale downward, does it work, or in that case does the window balloon up on a resize instead of shrinking down?

**Comment by nagalun** [comment]
> Out of curiosity, does this happen only if this scaling (is that a wayland thing?) happens to be >1? I.e., if you scale downward, does it work, or in that case does the window balloon up on a resize instead of shrinking down?

No buggy behavior seems to happen on scaling 50% and 75%, strangely enough. It also doesn't happen when the scaling is set to 200%. I haven't tested 300% but my guess is that would be fine too and it's mostly a fractional scaling thing.

**Comment by nagalun** [comment]
> My hunch is that Wayland might be the culprit here, some way or another. Would be interesting to see if similar programs with snap-to-grid scaling exhibit similar behaviour - could you try xterm?

Ah, interesting. Xterm has the same issue... Then it must be either KWin's fault (KDE's compositor), or something about xwayland + fractional scaling.

I haven't tried running it on GNOME yet, I tried weston as that's the reference compositor for wayland but it doesn't seem to support fractional scaling and completely ignores the increments when resizing anyways (and lags hard when doing so, but it might just be my machine).

I'll try GNOME next and depending on how that goes we'll conclude if it's a bug on xwayland or if KWin is at fault here, but knowing it happens on xterm I don't think this can really be considered a bug on Zutty's part as xterm is a pretty fundamental xorg app to test. You can close this issue if you wish.

Either way, I'll keep running zutty by patching out that call locally as I'd like to use it for now and it doesn't seem to affect functionality.

**Comment by nagalun** [comment]
Okay, apparently GNOME doesn't support sending info about any scaling at all to xwayland apps, and instead it scales them in a blurry mess, so I can't test my theory: https://old.reddit.com/r/gnome/comments/x1qbd2/has_anyone_solved_blurry_xwayland_apps_with/

Obviously on KDE if I set the xwayland option "Scaled by the system" even if I have the scaling set to 125% resizing works fine, but the text is scaled too and blurry, so it's no good. I'll see if I open a bug on KDE's side.

Thanks for your patience and sorry for the waste of time.

**Comment by tomscii** [comment]
No worries and thanks for confirming my suspicions about Wayland :)
