### ISSUE TITLE
double click selection doesnt stop on non-alnum chars

### ISSUE THREAD

**Issue by rofl0r** [tomscii/zutty#119]
in xterm, if you have `int main(void)` and double click on `main` only `main` gets selected.
in zutty, `main(void)` gets selected. i often use this feature to copy/paste function names, but with zutty i have to move the mouse around to get the proper part selected.

**Comment by tomscii** [comment]
1. In xterm, what character classes constitiute a "word" is actually configurable. What you describe reflects the _default_ behaviour of xterm.
2. In zutty this is much simpler and not user-configurable - only whitespace is understood to separate words.
3. As should be apparent from the above, zutty != xterm.
4. All this is documented, to make it clear that this is not a bug.

**Comment by rofl0r** [comment]
would you care to englighten me what the name of that configuration option is in xterm ?
and then, would you mind considering merging a well-done PR implementing the same configuration option ?

**Comment by tomscii** [comment]
man xterm, look for CHARACTER CLASSES.
I would be delighted to look at your pull request, and I am not categorically opposed to improving zutty in this area. HTH
