### ISSUE TITLE
GLSL ES 3.10 is not supported

### ISSUE THREAD

**Issue by Tux** [tomscii/zutty#126]
`Linux 5.14.21-150400.24.81-default [openSUSE Leap 15.4]`
```
$ ./waf configure -c yes --prefix=/pro/local
:
$ ./waf build
:
$ ./waf test
No function 'test' defined in /pro/3gl/zutty-git/wscript
$ ./waf install
:
```
```
$ zutty --version
E [charvdev.cc:277] Error: Compiling fragment shader:
0:1(10): error: GLSL ES 3.10 is not supported. Supported versions are: 1.00 ES, and 3.00 ES

terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
Abort (core dumped)
```
```
$ zutty --help
E [charvdev.cc:277] Error: Compiling fragment shader:
0:1(10): error: GLSL ES 3.10 is not supported. Supported versions are: 1.00 ES, and 3.00 ES

terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
Abort (core dumped)
```
Someone who likes zutty told me by mail that double-dash POSIX is not yet supported :(
```
$ zutty -help
Zutty 0.14-6-gf20049e
Copyright (C) 2020 Tom Szilagyi
```
It also does not install a manual page, so `man zutty` does not provide me with info I need to continue.
I hate dark background, and `zutty -bg "#fff" -fg "#000"` is not really user-friendly (if it would work at all on my system)

I am a happy xterm user, so no need to hurry. This is just feedback from a terminal-emulation-tester

**Comment by tomscii** [comment]
What you should have read before writing:
- https://github.com/tomscii/zutty/wiki/FAQ
- https://tomscii.sig7.se/zutty/doc/USAGE.html
