### ISSUE TITLE
"No Regular variant...font...identified.

### ISSUE THREAD

**Issue by ericjs** [tomscii/zutty#127]
It seems like I get this "No Regular variant of the requested font '____' could be identified" with fonts which do have what I would consider a "regular" version. (Example Everson Mono (https://evertype.com/emono/)). Is there some criteria for "Regular" being employed here which a non-font-expert user might not know, or is this maybe a bug? I've had this happen with a number of different fonts.

**Comment by tomscii** [comment]
read the FAQ
