### ISSUE TITLE
Regression from commit f20049e: issue with custom zutty bg color + tmux RGB color + custom tmux statusbar bg color

### ISSUE THREAD

**Issue by seankhl** [tomscii/zutty#129]
If I specify a zutty bg color as well as a tmux statusbar bg color, and I've set my tmux to use RGB color as recommended [in their docs](https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour), the tmux statusbar bg color clobbers the zutty bg color. Only if all three of these criteria are present does the issue occur. You can try to reproduce as follows:

1. Build the latest zutty as per the documentation instructions and start it using:

    ```bash
    zutty -bg '#111'
    ```
2. In zutty and with tmux 3.2 or above (I'm using 3.3a), start a tmux session with the following config (say, at `$HOME/.config/tmux/tmux.conf`):

    ```
    set -as terminal-overrides ',*-256color:Tc'
    set-option -g status-style bg='#444444'
    ```

On my machine, this causes the entire background to turn the color of the tmux statusbar background. If I check out the previous commit, the issue is not present.

Let me know if there's any further information I can provide!

**Comment by tomscii** [comment]
Thanks for finding this. Could you please verify the below patch?

```
modified   src/vterm.icc
@@ -1663,6 +1663,8 @@ namespace zutty
             break;
          }
       }
+      rgb_fg = opts.fg;
+      rgb_bg = opts.bg;
       setState (InputState::Normal);
    }
 
```

**Comment by seankhl** [comment]
Yep that fixes it for me! I appreciate the quick reply and patch!
