### ISSUE TITLE
Certain fonts don't display properly

### ISSUE THREAD

**Issue by iver0** [tomscii/zutty#130]
Tested with MesloLGS Nerd Font and Monaco Nerd Font, both result in this:

![image](https://github.com/tomscii/zutty/assets/81345597/6d5c837a-0b55-405e-849f-a1da98d9f8fc)

As seen - only the nerd glyphs are visible, and regular text is invisible. Changing colorscheme doesn't seem to affect the result. The issue isn't present with the default 9x18 font, but with it you don't get nerd glyphs. Tested on Pop!_OS, same result when both installing Zutty from apt and building it from source.

**Comment by tomscii** [comment]
You have a FAQ item to read.
