### ISSUE TITLE
I cannot get a bitmap font to work with zutty

### ISSUE THREAD

**Issue by vaskark** [tomscii/zutty#88]
I've added my local bitmap folder to my fontpath and tried to use one of the bitmap fonts stored there:

`/home/vaskark/.local/share/fonts/misc/cozette.bdf: Cozette:style=Regular
`

And ran:

`zutty -fontpath /home/vaskark/.local/share/fonts/misc -font Cozette -fontsize 12  
`

The error produced:

```
E [fontpack.cc:218] Error: No Regular variant of the requested font 'Cozette' could be identified.
terminate called after throwing an instance of 'std::runtime_error'
  what():  No suitable files for 'Cozette' found!
zsh: IOT instruction (core dumped)  zutty -fontpath /home/vaskark/.local/share/fonts/misc -font Cozette -fontsize 1
```
Not sure what I'm doing wrong. Actually I haven't been too successful with getting many of my fonts to work (and glyphs showing up). 6x12 seems to work for the starship prompt symbol. Not much else is, though.
Thanks. It's a great app.

**Comment by tomszilagyi** [comment]
Your filename does not match the required pattern. Please read the documentation for details.
On a meta-level, I think you want to use some of the well documented font alternatives (misc-fixed et al), unless you know what you are doing and/or are prepared to dig into it.
I am leaving this open for a while so feel free to come back with questions but please do not expect much hand-holding.

**Comment by vaskark** [comment]
Understood. I’ll keep at it.

**Comment by ZeusThundr** [comment]
I'm having the exact same issue with Cozzete and other bitmap font's could you suggest or confirm what the issue is or could be? Is it the filename?
I think it has to do with the name I've tried to symlink it to another name still nothing but this time its with the cozette.otb file instead of the bdf which I haven't tried.

**Comment by tomscii** [comment]
I guess you need to add ".bdf" as a recognized extension in fontpack.cc (line 100-ish).
Then get ready to debug all sorts of weird issues related to this new format.
Alternatively, try this font in an already well supported format.
ttf, otf and pcf.gz usually work fine.

**Comment by ZeusThundr** [comment]
Thank you for the quick response. For anyone else interested in this issue I found a package in the aur package (nerd-fonts-cozette-ttf ) which works, but its more of a hack as it renders slightly larger and messes up the letter spacing of the font making it look like a non-bitmap font as in its it look soft/ not crisp.

**Comment by tomscii** [comment]
Added a [FAQ entry](https://github.com/tomscii/zutty/wiki/FAQ#q-font-xyz-does-not-load-in-zutty-or-looks-crappy-what-should-i-do)
