### ISSUE TITLE
Extra "pty write" message in debug output

### ISSUE THREAD

**Issue by ttrei** [tomscii/zutty#93]
"zutty.dbg -v" outputs the data written to the pseudoterminal.

Depending on modifiers, the data may get printed twice:
```
T [vterm.cc:739] pty write (mod=0): 'q' (1 bytes)
T [vterm.cc:821] pty write: 'q' (1 bytes)
```

In the following example the modified ":" keypress was translated to a control sequence.
```
T [vterm.cc:739] pty write (mod=1): ':' (1 bytes)
T [vterm.cc:821] pty write: '\e[27;2;58~' (10 bytes)
```
I checked on the other side that only the 10-byte control sequence was actually written to the pseudoterminal.
The extra "pty write" may mislead one into thinking that 11 bytes were written here.

Without modifiers, there is only one "pty write" entry:
`T [vterm.cc:821] pty write: '\r' (1 bytes)`

Tested on zutty 0.13 (commit b7bc75148a0a15eda4f9b5437941949cf72ef5bd)

**Comment by tomscii** [comment]
I am not sure I understand the point of this issue. It's not an "extra" message. Sometimes multiple traces will be output as execution goes through the call stack. The point is that you can follow what happens, e.g., in this case `writePty (uint8_t ch, VtModifier modifiers, bool userInput)` on line 736 will call into `writePty (const uint8_t* ucstr, size_t len, bool userInput)` on line 812, the latter is a lower-level function.

**Comment by ttrei** [comment]
My claim is that the person doing the debugging may get confused. I know I was :)

The developer guide shows example output from an older version of zutty:
```
T [vterm.icc:366] pty write (mod=0): 'k' (1 bytes)
T [vterm.icc:400] pty read: 'k' (1 bytes)
```
Notice only one "pty write" message.
And it further explains:
> Following the trace log, we can see that first the keypress was sent to the shell (pty write), then the echoed character was read back from the shell (pty read), which triggered an insertion of k as text.

Naturally, I assumed that each "pty write" message reflects an actual write to the pty.

Here is how the same input looks in zutty 0.13:
```
T [vterm.cc:739] pty write (mod=0): 'k' (1 bytes)
T [vterm.cc:821] pty write: 'k' (1 bytes)
T [vterm.icc:384] pty read: 'k' (1 bytes)
```
In this case it may be obvious that both "pty write" messages refer to the same write.
But it is not so obvious when the second "pty write" shows something entirely different, like here:
```
T [vterm.cc:739] pty write (mod=1): ':' (1 bytes)
T [vterm.cc:821] pty write: '\e[27;2;58~' (10 bytes)
```

**Comment by tomscii** [comment]
I don't see any issue here.
