### ISSUE TITLE
Deviation from xterm's modifyOtherKeys behavior when only Shift modifier active

### ISSUE THREAD

**Issue by ttrei** [tomscii/zutty#94]
When modifyOtherKeys is 2, zutty translates "*" (without any modifier key other than Shift pressed) to the escape sequence "\e[27;2;42~":
```
T [vterm.cc:739] pty write (mod=1): '*' (1 bytes)
T [vterm.cc:821] pty write: '\e[27;2;42~' (10 bytes)
```
xterm doesn't do this translation.

Other symbols are also affected.

xterm source tree contains `vttests/modify-keys.pl` script that illustrates xterm's behavior in different modifyOtherKeys modes.
Output of the script on my machine: [xterm-modify-keys.txt](https://github.com/tomscii/zutty/files/9846994/xterm-modify-keys.txt)
Excerpt:
```
(snip)
Other modified-key escapes:
Code Symbol Actual                  Mode 0         Mode 1         Mode 2
(snip)
0x002a XK_asterisk          42     -(skip)-       --******       --******
----                               *              *              *
s---                               *              *              *
-a--                               *              \E[27;3;42~    \E[27;3;42~
sa--                               *              \E[27;4;42~    \E[27;4;42~
--c-                               *              \E[27;5;42~    \E[27;5;42~
s-c-                               *              \E[27;6;42~    \E[27;6;42~
-ac-                               *              \E[27;7;42~    \E[27;7;42~
sac-                               *              \E[27;8;42~    \E[27;8;42~
(snip)
```
We can see that if only the Shift modifier is active, xterm outputs "*", not an escape-sequence.

This zutty behavior breaks the visual-star search feature in neovim
(on startup neovim instructs the terminal to go into modifyOtherKeys=2 mode)
```
nvim -u NONE <file>
# Enter VISUAL mode, select some text, press *
# expected: neovim exits VISUAL mode and searches for next occurrence of the selected text
# actual: neovim stays in VISUAL mode and extends the current selection
```
The visual-star search works as expected in xterm.

Versions:
xterm 374
neovim v0.8.0
zutty 0.13

Tried out a quick hack to avoid the translation to escape sequence, and it fixes the neovim behavior:
Replace the following line at https://github.com/tomscii/zutty/blob/b7bc75148a0a15eda4f9b5437941949cf72ef5bd/src/vterm.cc#L742 
with
```
if ((modifyOtherKeys == 2 && modifiers != VtModifier::none
        && (modifiers & VtModifier::shift) == VtModifier::none) ||
```

**Comment by tomscii** [comment]
Yeah, I wonder why this inconsistency exists (and opted to break it in Zutty). I thought the point of setting modifyOtherKeys to 2 was to get *all* keys encoded. But apparently if some keys get encoded, certain programs get confused. Sigh...

**Comment by tomscii** [comment]
Can you please try this and see if there are any discrepancies left?

```
modified   src/vterm.cc
@@ -739,7 +739,22 @@ namespace zutty
       logT << "pty write (mod=" << (int)modifiers << "): "
            << dumpBuffer (uch, uch + 1);
 
-      if ((modifyOtherKeys == 2 && modifiers != VtModifier::none) ||
+      const auto& mod2_nonexempt =
+         [] (uint8_t ch)
+         {
+            const char* exempt = "+=!#$%&*()[]-/?:\"<>";
+            auto x = const_cast <char*> (exempt);
+
+            while (*x)
+               if (ch == *x++)
+                  return false;
+
+            return true;
+         };
+
+      if ((modifyOtherKeys == 2 &&
+           modifiers != VtModifier::none &&
+           mod2_nonexempt (ch)) ||
           (modifyOtherKeys == 1 &&
            (modifiers & VtModifier::control) != VtModifier::none &&
            ch > ' '))
```

**Comment by tomscii** [comment]
Scratch that, it makes Ctrl+Shift+3 encode to # instead of `CSI ; 6 ; 35 ~` ...

**Comment by tomscii** [comment]
This should work better:

```
modified   src/vterm.cc
@@ -739,7 +739,20 @@ namespace zutty
       logT << "pty write (mod=" << (int)modifiers << "): "
            << dumpBuffer (uch, uch + 1);
 
-      if ((modifyOtherKeys == 2 && modifiers != VtModifier::none) ||
+      const auto& mod2_encode =
+         [&] (uint8_t ch)
+         {
+            const char* exempt = "+=!#$%&*()[]-/?:\"<>";
+            auto x = const_cast <char*> (exempt);
+
+            while (*x)
+               if (ch == *x++)
+                  return (modifiers & VtModifier::control_alt) != VtModifier::none;
+
+            return modifiers != VtModifier::none;
+         };
+
+      if ((modifyOtherKeys == 2 && mod2_encode (ch)) ||
           (modifyOtherKeys == 1 &&
            (modifiers & VtModifier::control) != VtModifier::none &&
            ch > ' '))
```

**Comment by ttrei** [comment]
I confirm that the patch fixes the neovim problem that prompted me to investigate this.

I grepped through the modify-keys.pl output for "s---" and found these candidates for exemption:
`! " # $ % & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ?`
Characters that are not in your exemption list: `' , . 0 1 2 3 4 5 6 7 8 9 ;`.
Characters that are in your exemption list but are encoded by xterm: `[ ] \`.

There are also other more exotic characters that are not encoded by xterm, like currency symbols:
```
0x00a3 XK_sterling          163    -(skip)-       --******       --******       
----                               £              £              £              
s---                               £              £              £              
-a--                               £              \E[27;3;163~   \E[27;3;163~   
sa--                               £              \E[27;4;163~   \E[27;4;163~   
--c-                               £              \E[27;5;163~   \E[27;5;163~   
s-c-                               £              \E[27;6;163~   \E[27;6;163~   
-ac-                               £              \E[27;7;163~   \E[27;7;163~   
sac-                               £              \E[27;8;163~   \E[27;8;163~   
```
Here are some of them:
```¡ ¢ £ ¦ « ° ± ² ³ ´ · ¹ » ½ ¾ ¿ × ÷ Ƣ Ʃ Ʈ ƹ ƾ Ǩ ǿ Σ Φ Ϊ Ϋ γ ζ κ λ π ϑ ϒ ϓ Ϟ Ϡ ϱ ϲ ϳ Ͼ €```

I think it would be very valuable to test these encodings automatically. Otherwise very easy to miss something.
Does vttest provide some way to check these?
The modify-keys.pl script is described as "illustration":
https://github.com/ThomasDickey/xterm-snapshots/blob/726c9e4320d7d0b37a60a5ad32460ade262a87c5/vttests/modify-keys.pl#L34

**Comment by tomscii** [comment]
> I confirm that the patch fixes the neovim problem that prompted me to investigate this.

Thanks!

> I grepped through the modify-keys.pl output for "s---" and found these candidates for exemption: `! " # $ % & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ?` Characters that are not in your exemption list: `' , . 0 1 2 3 4 5 6 7 8 9 ;`. Characters that are in your exemption list but are encoded by xterm: `[ ] \`.

Yeah, the exemption list is not the whole story, as there are other code paths at play.

For example, if you try with xterm and (patched) zutty side-by-side, you will (hopefully) see identical results for all the characters, even those you listed as a difference re. the exemption list. E.g., `' , .` and the digits are entered without modifiers, so they won't be encoded at all, same for `[ ] \`.

The ones normally accessed via shift (e.g., `!` as shift-1) should be in the exemption list so as not to get mod2-encoded when shift is the only modifier.

I'm wondering about the role of keyboard layouts here, `[ ] \` are entered direct (without shift) on my US keyboard, hence they are not in the exemption list, but maybe they should be (to guard against being entered with shift on other layouts). But the digits I'm fairly sure can be left out.

> 
> There are also other more exotic characters that are not encoded by xterm, like currency symbols:
> 
> ```
> 0x00a3 XK_sterling          163    -(skip)-       --******       --******       
> ----                               £              £              £              
> s---                               £              £              £              
> -a--                               £              \E[27;3;163~   \E[27;3;163~   
> sa--                               £              \E[27;4;163~   \E[27;4;163~   
> --c-                               £              \E[27;5;163~   \E[27;5;163~   
> s-c-                               £              \E[27;6;163~   \E[27;6;163~   
> -ac-                               £              \E[27;7;163~   \E[27;7;163~   
> sac-                               £              \E[27;8;163~   \E[27;8;163~   
> ```
> 
> Here are some of them: `¡ ¢ £ ¦ « ° ± ² ³ ´ · ¹ » ½ ¾ ¿ × ÷ Ƣ Ʃ Ʈ ƹ ƾ Ǩ ǿ Σ Φ Ϊ Ϋ γ ζ κ λ π ϑ ϒ ϓ Ϟ Ϡ ϱ ϲ ϳ Ͼ €`

Yeah, I frankly don't care so much about these. None of them are accessible on my keyboard, so it's more of a theoretical issue. But if someone complains I can always add an exemption for it...

> 
> I think it would be very valuable to test these encodings automatically. Otherwise very easy to miss something. Does vttest provide some way to check these? The modify-keys.pl script is described as "illustration": https://github.com/ThomasDickey/xterm-snapshots/blob/726c9e4320d7d0b37a60a5ad32460ade262a87c5/vttests/modify-keys.pl#L34

The zutty automated test `keys.sh` covers this area (at least to a good part, if not 100%). It's not that this is not tested, the problem is coming up with the "right" behaviour to verify.

**Comment by ttrei** [comment]
Regarding `[ ] \` - my point was that they _are in_ your exemption list but should not be, since xterm supposedly doesn't encode them when only shift modifier is active.

Otherwise I have no more suggestions or requests.
Also, thank you for creating zutty :) It's been my go-to terminal for a couple of years already and has been rock-solid.

**Comment by tomscii** [comment]
Fair enough - on my keyboard these are typed without shift, hence I did not include them. But adding them is the safer option, will do that.

Also appreciate your kind words, I don't get that much feedback apart from a steady stream of issues and complaints. :)
