### ISSUE TITLE
Packaged Zutty upstream for openSUSE Tumbleweed

### ISSUE THREAD

**Issue by bverhagen** [tomscii/zutty#95]
First of all: thank you @tomscii  for creating this great terminal emulator! I am a happy user of your system for multiple years now.

I just wanted to inform you that I packaged Zutty 0.13 for openSUSE Tumbleweed. It recently got accepted into 'SUSE:factory', which basically means that you can install it from the default repositories straight from a clean install (You can test it by running `zypper install zutty` in the `opensuse/tumbleweed` container).

Is this something you see fit to be added to this repositories' documentation or do you want to keep this completely separate (I could not find any other upstream mention of a repository in the docs)?

**Comment by tomscii** [comment]
You are welcome.

I do not even try to keep a list of who has packaged Zutty (anyone can do it and they are not obliged to tell me about it, plus I do not really have time for such administrivia...), but I sure hope they all keep their packages meticulously updated.
