### ISSUE TITLE
Shift/Ctrl-Enter produce uninterpreted escape code

### ISSUE THREAD

**Issue by jengelh** [tomscii/zutty#97]
In a zutty 0.13 window, the key combination Shift-Enter produces the sequence `\e[27;2;13~`, and Ctrl-Enter yields `\e[27;5;13~`. The foreground program (e.g. bash) running in zutty does not know what to do with this and part of the sequence (`;2;13~`) is treated as user input.
Under xterm, shift/ctrl-Enter seems to be equivalent to just enter.

**Comment by tomscii** [comment]
This is the normal behaviour with modifyOtherKeys > 0, as documented here: https://tomscii.sig7.se/zutty/doc/KEYS.html#Special%20key%20combinations
I see the same in xterm (with keyboardType=vt220 which is what Zutty emulates).
