### ISSUE TITLE
ligatures support and some fix docs

### ISSUE THREAD

**Issue by n1rdeks** [tomscii/zutty#99]
Please, add Ligatures support (PragmataPro, Fira or others fonts)

And fix docs, about config .Xresources

```
Zutty.font - filename, not font name!
Zutty.fontsize - in pixels
```

Thanks.

**Comment by tomscii** [comment]
https://github.com/tomscii/zutty/wiki/FAQ#q-why-would-i-not-want-to-use-zutty

**Comment by n1rdeks** [comment]
)) And please fix docs about
https://github.com/tomscii/zutty/wiki/FAQ#q-why-would-i-not-want-to-use-zutty

>transparent backgrounds

With picom all works fine ;)) Just set on picom.conf
```
opacity-rule = [
  "90:class_g = 'Zutty'",
];
```
but my default terminal is ST )) Girlfriend (love Gentoo) advised me watch on Zutty.
